rvm: 1.8.7
bundler_args: ''
notifications:
  email:
    - jeffery.rukundo@gmail.com
env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.2.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.3.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.4.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.5.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.6.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
